Repository LearningLocker/learninglocker, pull requests merged in 2018-08, with the labels that each got.

#1216 refactor(requeue)
  cli/src/commands/requeueStatements.js
  worker/src/handlers/statement/statementHandler.js
Labels: QA NEEDED

#1184 LL-405 Can delete un-completed exports if they're over a day old.
  ui/src/components/DownloadListItem/index.js
  ui/src/redux/modules/models/pollWhile.js
  yarn.lock
Labels: QA PASSED

#1131 LL-562 Upgraded to node v8.11.1
  .travis.yml
  package.json
  yarn.lock
Labels: QA PASSED

#1202 LL-599 Fixed query handling null.
  ui/src/containers/VisualiseForm/StatementsForm/AxesEditor/QueryEditor.js
Labels: QA NEEDED

#1192 v2.5.0
  .travis.yml
  CHANGELOG.md
  VERSION
  api/src/auth/passport.js
  api/src/routes/tests/DBHelper.js
  lib/constants/dashboard.js
  lib/models/dashboard.js
  lib/models/organisation.js
  lib/models/user.js
  lib/routes/index.js
  lib/services/files/exportStatements.js
  lib/services/statements/aggregate.js
  lib/services/statements/utils/checkDashboardAuth.js
  lib/utils/validators/common.js
  package.json
  pm2/all.json
  pm2/all.json.dist
  pm2/dev-all.json
  pm2/server.json
  pm2/webapp.json.dist
  pm2/worker.json
  pm2/worker.json.dist
  ui/src/components/DownloadListItem/index.js
  ui/src/components/ExportForm/index.js
  ui/src/containers/DashboardSharing/index.js
  ui/src/containers/DashboardSharing/styles.css
  ui/src/containers/ModelListItem/ModelListItemWithoutModel.js
  ui/src/containers/Personas/PersonasImports/columnHeaderEditor/__snapshots__/HeaderItem.spec.js.snap
  ui/src/containers/Personas/PersonasImports/index.js
  ui/src/containers/SubOrgForm/index.js
  ui/src/containers/Users/index.js
  ui/src/containers/VisualiseForm/StatementsForm/AxesEditor/QueryEditor.js
  ui/src/redux/modules/logo.js
  ui/src/redux/modules/models/pollWhile.js
  ui/src/redux/modules/models/updateModel.js
  ui/src/redux/modules/pagination/fetchModelsCount.js
  ui/src/redux/modules/visualise.js
  ui/src/utils/dashboard.js
  worker/src/handlers/importPersonas/importPersonaHandler.js
  worker/src/handlers/statement/index.js
  yarn.lock
Labels: DO NOT MERGE

#1238 Removed editing and deleting visualisation from dashboard.
  ui/src/components/AutoComplete2/Inputs/SingleInput/ModelInput.js
  ui/src/components/AutoComplete2/Option/EditableOption.js
  ui/src/components/AutoComplete2/Options/ModelOptionList/ModelOptionList.js
  ui/src/containers/ModelAutoComplete/index.js
  ui/src/containers/WidgetVisualisePicker/index.js
Labels: QA PASSED

#1239 LL-629 Fixed restify crashing if invalid id is sent.
  lib/constants/auth.js
Labels: QA PASSED

#1234 v2.5.1
  CHANGELOG.md
  VERSION
  lib/constants/auth.js
  lib/services/statements/utils/checkDashboardAuth.js
  package.json
Labels: QA PASSED

#1243 Issue ll 5
  ui/src/components/AutoComplete2/Option/EditableOption.js
  yarn.lock
Labels: QA PASSED

#1244 Fixed editing saved queries.
  ui/src/components/AutoComplete2/Inputs/SingleInput/ModelInput.js
  ui/src/components/AutoComplete2/Inputs/SingleInput/SingleInput.js
  ui/src/components/AutoComplete2/Options/ModelOptionList/ModelOptionList.js
  ui/src/components/AutoComplete2/Options/OptionList/InfiniteOptionList.js
  ui/src/components/AutoComplete2/index.js
  ui/src/components/TextInput/index.js
  ui/src/components/TextInput/styles.css
  ui/src/components/TextInputGroup/index.js
  ui/src/components/TextInputGroup/styles.css
  ui/src/containers/ModelAutoComplete/index.js
Labels: QA PASSED
