Repository LearningLocker/learninglocker, pull requests merged in 2019-04, with the labels that each got.

#1335 Added azure storage support.
  .env.example
  lib/services/files/storage/azure.js
  lib/services/files/storage/index.js
  package.json
  yarn.lock
Labels: QA PASSED, Type: Feature

#1340 Support PORT in addition to UI_PORT
  ui/src/config.js
Labels: Type: Feature

#1325 Fixed addCrudFunctions recursively importing.
  lib/services/auth/authInfoSelectors/isOrgOwnerInAuthInfo.js
  lib/services/auth/filters/utils/getModelsFilter.js
  lib/services/auth/modelFilters/organisation.js
  lib/services/auth/modelFilters/visualisation.js
  lib/services/auth/tests/modelFilters/visualisation-test.js
Labels: QA PASSED, Type: Fix

#1347 Add option sampleSize to efficiently sample statements, fixes 1291
  api/src/controllers/StatementController.js
  lib/models/statement.js
  lib/services/statements/aggregate.js
Labels: QA PASSED, Type: Feature

#1360 feat(Import Personas): Allow persona imports via client auth
  api/src/routes/HttpRoutes.js
Labels: QA PASSED, Type: Feature

#1355 fix(Workers): Handle deleted statements
  worker/src/handlers/statement/wrapHandlerForStatement.js
Labels: QA PASSED, Type: Fix
