Repository LearningLocker/learninglocker, pull requests merged in 2019-02, with the labels that each got.

#1298 LL-693 Fix missing cells in table
  ui/src/containers/VisualiseResults/SourceResults.js
Labels: LL-UI, QA PASSED

#1293 refactor: Removes unused code.
  lib/constants/graphql.js
  lib/constants/routes.js
  package.json
  ui/src/containers/AddButton/AddButton.js
  ui/src/redux/modules/exports/index.js
  yarn.lock
Labels: QA PASSED

#1280 LL-688 fixed overlapping chart legends
  ui/src/components/Charts/Chart.js
  ui/src/components/Charts/PieChart.js
  ui/src/components/Charts/__snapshots__/PieChart.spec.js.snap
Labels: QA PASSED

#1310 feat: Add new route for issuing OAuth2 access_token
  api/src/auth/passport.js
  api/src/controllers/AuthController.js
  api/src/routes/HttpRoutes.js
  api/src/routes/tests/DBHelper.js
  api/src/routes/tests/http-test.js
  api/src/server.js
  cli/src/commands/v2-migrations/20190131000000_oauth_tokens.js
  cli/src/commands/v2-migrations/index.js
  lib/constants/auth.js
  lib/constants/routes.js
  lib/models/oAuthToken.js
Labels: LL-API

#1318 findAndModify rewrites
  api/src/controllers/StatementMetadataController.js
  api/src/routes/tests/DBHelper.js
  api/src/routes/tests/utils/setup.js
  api/src/utils/tests/exports-test.js
  api/src/utils/tests/exportsDBHelper.js
  cli/src/commands/disableRegister.js
  cli/src/commands/expirationNotificationEmails-test.js
  cli/src/commands/migrateExportsToCSV.js
  cli/src/commands/updateClientOrganisation.js
  cli/src/commands/updateStatementOrganisation.js
  cli/src/commands/v1-migrations/migrateClientAuthority.js
  cli/src/commands/v1-migrations/migrateClientId.js
  cli/src/commands/v1-migrations/migrateTimestamps.js
  cli/src/commands/v1-migrations/migrateXAPIReadScope.js
  cli/src/commands/v2-migrations/20171121153300_update_refs.js
  cli/src/commands/v2-migrations/20171127214900_migrate_identifiers.js
  cli/src/commands/v2-migrations/20180212_expiration.js
  cli/src/commands/v2-migrations/20180320093000_shareable_dashboards.js
  cli/src/migrateMongo/migrateMongo-test.js
  cli/src/server.js
  lib/connections/mongoose.js
  lib/constants/statements.js
  lib/models/lrs.js
  lib/models/organisation.js
  lib/models/plugins/addCRUDFunctions.js
  lib/models/role-test.js
  lib/models/role.js
  lib/models/user.js
  lib/services/auth/tests/utils/setup.js
  lib/services/importPersonas/getStructure-test.js
  lib/services/importPersonas/importPersona.js
  lib/services/importPersonas/importPersonas-test.js
  lib/services/importPersonas/importPersonas.js
  lib/services/importPersonas/uploadPersonas-test.js
  lib/services/importPersonas/uploadPersonas.js
  lib/services/persona/asignIdentifierToStatements.js
  lib/services/persona/reasignPersonaStatements.js
  lib/services/persona/tests/reasignPersonaStatements-test.js
  lib/services/querybuildercache/addIdentsToCache/index-test.js
  lib/services/querybuildercache/getCachesFromStatement/fixtures.js
  package.json
  worker/src/handlers/importPersonas/importPersonaHandler-test.js
  worker/src/handlers/importPersonas/importPersonaHandler.js
  worker/src/handlers/statement/batcher.js
  worker/src/handlers/statement/lrscountHandler.js
  worker/src/handlers/statement/statementForwarding/statementForwardingDeadLetterHandler.js
  worker/src/handlers/statement/statementForwarding/statementForwardingRequestHandler.js
  worker/src/handlers/statement/statementForwarding/tests/statementForwardingDeadLetterHandler-test.js
  worker/src/handlers/statement/statementForwarding/tests/statementForwardingHandler-test.js
  worker/src/handlers/statement/statementForwarding/tests/statementForwardingRequestHandler-test.js
  worker/src/handlers/statement/statementHandler.js
  worker/src/handlers/statement/tests/extractPersonasHandler-test.js
  worker/src/handlers/statement/tests/queryBuilderCacheDBHelper.js
  yarn.lock
Labels: QA PASSED

#1303 LL-681: Add Result.response to query builder and grouping
  cli/src/commands/updateStatementCount.js
  ui/src/components/AutoComplete2/Inputs/MultiInput/QueryBuilderInput.js
  ui/src/components/Counter/index.js
  ui/src/components/MultiInput/index.js
  ui/src/components/MultiInput/styles.css
  ui/src/components/TextInputGroup/index.js
  ui/src/components/Token/index.js
  ui/src/components/Token/styles.css
  ui/src/containers/BasicQueryBuilder/ExpandedSection.js
  ui/src/containers/BasicQueryBuilder/StringMatches/Criteria.js
  ui/src/containers/BasicQueryBuilder/StringMatches/Criterion.js
  ui/src/containers/VisualiseResults/CounterResults.js
  ui/src/redux/modules/queryBuilder.js
  ui/src/utils/visualisations/helpers/keyExists.js
  ui/src/utils/visualisations/localOptions.js
  ui/src/utils/visualisations/projections/group.js
  ui/src/utils/visualisations/projections/model.js
  ui/src/utils/visualisations/projections/value.js
Labels: LL-UI, QA PASSED

#1320 Organisation scopes css.
  ui/src/containers/RoleForm/index.js
  ui/src/containers/RoleForm/styles.css
Labels: QA PASSED

#1323 LL-642 fix: Fixes mixed dependencies to close #1302.
  package.json
Labels: QA PASSED

#1297 LL-345 Fix grouping by Persona.Import in visualisations
  cli/src/commands/v2-migrations/20190212150000_personaAttributes_indexes.js
  cli/src/commands/v2-migrations/index.js
  ui/src/utils/visualisations/aggregationGroup/grouper/index.js
  ui/src/utils/visualisations/aggregationGroup/grouper/index.spec.js
Labels: DO NOT MERGE, LL-UI, MONGO-UPGRADE-REQUIRED, QA PASSED

#1300 LL-703 feat: Adds option to forward attachments.
  lib/models/statementForwarding.js
  lib/services/querybuildercache/getCachesFromStatement/index.js
  package.json
  ui/src/components/StatementForwarding/StatementForwardingForm.js
  worker/src/handlers/statement/statementForwarding/getStatementsRepo.js
  worker/src/handlers/statement/statementForwarding/statementForwardingRequestHandler.js
  worker/src/handlers/statement/statementForwarding/tests/statementForwardingHandler-test.js
  worker/src/handlers/statement/statementForwarding/tests/statementForwardingRequestHandler-test.js
  yarn.lock
Labels: QA PASSED, type:enhancement

#1295 LL-636 feat: Add tracking each org's disk usage
  cli/src/commands/orgUsageTracker-test.js
  cli/src/commands/orgUsageTracker.js
  cli/src/scheduler.js
  cli/src/server.js
  lib/constants/orgUsageTracker.js
  lib/models/index.js
  lib/models/orgUsageStats.js
  lib/models/organisation.js
  lib/models/statement.js
  lib/models/statementOrgSample.js
  lib/models/statementSample.js
  pm2/all.json.dist
  ui/src/containers/SubOrgForm/index.js
  worker/src/handlers/orgUsageTracker/index.js
  worker/src/handlers/orgUsageTracker/initializeOrgStatsList.js
  worker/src/handlers/orgUsageTracker/orgUsageTracker.js
  worker/src/handlers/orgUsageTracker/totalUsage-test.js
  worker/src/handlers/orgUsageTracker/totalUsage.js
  worker/src/server.js
Labels: QA: PASSED, Type: Feature
