Repository LearningLocker/learninglocker, pull requests merged in 2019-03, with the labels that each got.

#1326 Requeue statement forwards
  worker/src/handlers/statement/statementForwarding/statementForwardingHandler.js
Labels: Type: Fix

#1329 fix(Indexes): Change statement.id index to ignore organisation
  cli/src/commands/v2-migrations/20171122100800_common_indexes.js
Labels: Type: Performance

#1322 Moved the persona lock to after validation.
  lib/services/importPersonas/establishLock.js
  lib/services/importPersonas/importPersona.js
  worker/src/handlers/importPersonas/importPersonaHandler-test.js
  worker/src/handlers/importPersonas/importPersonaHandler.js
Labels: QA PASSED, Type: Fix

#1331 LL-663 fix: writing-mode of y axis labels
  ui/src/components/Charts/styles.css
  ui/src/components/XvsY/styles.css
Labels: QA PASSED, Type: Fix

#1314 LL-704 feat: Add contextActivities.definition.type filter
  ui/src/containers/VisualiseForm/StatementsForm/AxesEditor/BarAxesEditor.js
  ui/src/containers/VisualiseForm/StatementsForm/AxesEditor/BaseAxesEditor.js
  ui/src/containers/VisualiseForm/StatementsForm/AxesEditor/ColumnAxesEditor.js
  ui/src/containers/VisualiseForm/StatementsForm/AxesEditor/DefinitionTypeSelector.js
  ui/src/containers/VisualiseForm/StatementsForm/AxesEditor/PieAxesEditor.js
  ui/src/containers/VisualiseForm/StatementsForm/AxesEditor/ScatterAxesEditor.js
  ui/src/containers/VisualiseForm/StatementsForm/Editor.js
  ui/src/containers/VisualiseForm/StatementsForm/StatementsForm.js
  ui/src/utils/visualisations/aggregateChart.js
  ui/src/utils/visualisations/aggregateXvsY.js
  ui/src/utils/visualisations/aggregationGroup/grouper/index.js
  ui/src/utils/visualisations/index.js
  ui/src/utils/visualisations/isContextActivity.js
Labels: QA PASSED, Type: Feature

#1337 fix(Client Page): Improves clarity for basic auth.
  lib/services/importPersonas/establishLock.js
  lib/services/importPersonas/importPersona.js
  ui/src/containers/ClientForm/__tests__/__snapshots__/ClientForm.spec.js.snap
  ui/src/containers/ClientForm/index.js
  worker/src/handlers/importPersonas/importPersonaHandler.js
  worker/src/handlers/orgUsageTracker/totalUsage.js
Labels: QA PASSED, Type: Fix

#1341 Persona merges now skip empty account ifis.
  lib/services/importPersonas/personasImportHelpers-test.js
  lib/services/importPersonas/personasImportHelpers.js
Labels: QA PASSED, Type: Fix

#1345 fix(Workers): Add better error logging to SQS failures
  lib/services/queue/sqs/index.js
  worker/src/handlers/statement/wrapHandlerForStatement.js
Labels: Type: Feature

#1333 LL-719 Add Apps page
  lib/routes/index.js
  ui/src/containers/Apps/AppCard.js
  ui/src/containers/Apps/icons/curatr.png
  ui/src/containers/Apps/icons/curatr@2x.png
  ui/src/containers/Apps/icons/index.js
  ui/src/containers/Apps/icons/moodle.png
  ui/src/containers/Apps/icons/moodle@2x.png
  ui/src/containers/Apps/icons/sparks.png
  ui/src/containers/Apps/icons/sparks@2x.png
  ui/src/containers/Apps/index.js
  ui/src/containers/Apps/styles.css
  ui/src/containers/OrganisationHome/index.js
  ui/src/containers/SideNav/index.js
Labels: QA PASSED, Type: Feature
