Repository LearningLocker/learninglocker, pull requests merged in 2019-05, with the labels that each got.

#1349 feat: Add visualisation templates
  lib/constants/visualise.js
  lib/models/visualisation.js
  ui/src/containers/VisualiseForm/StatementsForm/Editor.js
  ui/src/containers/VisualiseForm/StatementsForm/NewVisualisation/TemplateCard.js
  ui/src/containers/VisualiseForm/StatementsForm/NewVisualisation/TemplateIntermediateStage.js
  ui/src/containers/VisualiseForm/StatementsForm/NewVisualisation/TypeEditor.js
  ui/src/containers/VisualiseForm/StatementsForm/NewVisualisation/index.js
  ui/src/containers/VisualiseForm/StatementsForm/NewVisualisation/styles.css
  ui/src/containers/VisualiseForm/StatementsForm/NewVisualisation/templateData.js
  ui/src/containers/VisualiseForm/StatementsForm/StatementsForm.js
  ui/src/utils/defaultTitles.js
Labels: QA PASSED, Type: Feature

#1343 feat: Adds new Aggregation API to improve caching.
  .env.example
  api/src/controllers/StatementController.js
  api/src/routes/HttpRoutes.js
  api/src/routes/tests/http-test.js
  lib/constants/routes.js
  lib/models/statement-test.js
  lib/models/statement.js
  lib/services/statements/aggregate.js
  lib/services/statements/aggregateAsync.js
  lib/services/statements/index.js
  ui/src/components/Charts/__snapshots__/PieChart.spec.js.snap
  ui/src/components/Graphs/NoData.js
  ui/src/components/Graphs/index.js
  ui/src/redux/modules/aggregation/fetchAggregation.js
  ui/src/redux/modules/aggregation/index.js
  ui/src/redux/modules/visualise.js
  ui/src/redux/modules/visualise.spec.js
  ui/src/utils/LLApiClient.js
  ui/src/utils/createAsyncDuck.js
  ui/src/utils/hocs/withStatementsVisualisation.js
  ui/src/utils/visualisations/pipelinesFromQueries.js
Labels: QA PASSED, Type: Feature

#1346 feat: Allows deletion of statements (single and batch).
  .env.example
  api/src/controllers/BatchDeleteController.js
  api/src/routes/HttpRoutes.js
  api/src/routes/tests/batchDeleteController/batchDeletion-intiailise-test.js
  api/src/routes/tests/batchDeleteController/batchDeletion-terminate-test.js
  api/src/routes/tests/batchDeleteController/batchDeletion-terminateAll-test.js
  api/src/routes/tests/utils/models/createClient.js
  api/src/routes/tests/utils/setup.js
  api/src/routes/tests/utils/tokens/createClientToken.js
  cli/src/migrateMongo/index.js
  cli/src/migrateMongo/migrateMongo-test.js
  cli/src/scheduler.js
  cli/src/scheduler/batchDelete-test.js
  cli/src/scheduler/batchDelete.js
  lib/constants/batchDelete.js
  lib/constants/routes.js
  lib/constants/scopes.js
  lib/models/batchDelete.js
  lib/models/siteSettings.js
  lib/models/statement.js
  lib/services/auth/filters/getScopeFilter.js
  lib/services/auth/modelFilters/batchDelete.js
  lib/services/auth/modelFilters/statement.js
  lib/services/auth/tests/modelFilters/statement-test.js
  lib/services/auth/tests/utils/testClientBasicScopeFilter.js
  lib/services/queue/index.js
  lib/services/queue/sqs/index.js
  pm2/dev-all.json
  storage/statements/.gitignore
  ui/src/containers/ClientForm/__tests__/ClientForm.spec.js
  ui/src/containers/ClientForm/__tests__/__snapshots__/ClientForm.spec.js.snap
  ui/src/containers/ClientForm/index.js
  ui/src/controllers/renderApp.js
  worker/src/handlers/batchStatementDeletion/batchStatementDeletion-test.js
  worker/src/handlers/batchStatementDeletion/batchStatementDeletion.js
  worker/src/handlers/batchStatementDeletion/index.js
  worker/src/server.js
Labels: Type: Feature

#1366 Fix most popular activities template
  ui/src/containers/VisualiseForm/StatementsForm/NewVisualisation/templateData.js
Labels: Type: Fix

#1368 Fix query building of 'Store'
  ui/src/redux/modules/queryBuilder.js
Labels: Type: Fix

#1370 fix(JWTAuthentication): unexpected 500 responses
  api/src/auth/passport.js
Labels: Type: Fix

#1375 fix(QueryBuilder) query building of contextActivities
  ui/src/redux/modules/queryBuilder.js
Labels: QA PASSED

#1373 Issue 939 - Add security headers to dashboard
  ui/src/controllers/renderApp.js
Labels: QA PASSED, Type: Fix

#1372 Issue 942 - Login messages
  api/src/controllers/AuthController.js
  lib/models/user.js
  ui/src/containers/ForgotPassword/index.js
Labels: QA PASSED, Type: Fix

#1363 Issue 936 - API selects
  api/src/routes/HttpRoutes.js
  lib/services/auth/selects/models/user.js
  ui/src/redux/middleware/userMiddleware.js
Labels: QA PASSED, Type: Fix

#1359 Issue 937 - $lookup
  api/src/controllers/BatchDeleteController.js
  api/src/controllers/PersonaAttributeController.js
  api/src/controllers/PersonaController.js
  api/src/controllers/PersonaIdentifierController.js
  lib/constants/auth.js
  lib/helpers/convert$personaIdent.js
  lib/helpers/filter$lookup.js
  lib/helpers/parseQuery.js
  lib/helpers/tests/convert$personaIdent-test.js
  lib/helpers/tests/filter$lookup-test.js
  lib/models/plugins/addCRUDFunctions.js
  lib/models/statement.js
  lib/services/auth/authInfoSelectors/getOrgFromAuthInfo.js
  lib/services/auth/modelFilters/statement.js
  lib/services/statements/countStatements.js
  worker/src/handlers/batchStatementDeletion/batchStatementDeletion.js
  worker/src/handlers/statement/statementForwarding/statementForwardingHandler.js
Labels: QA PASSED, Type: Fix

#1358 Issue 938 - Reset tokens
  cli/src/commands/createSiteAdmin.js
  cli/src/commands/v2-migrations/20180411160000_site_settings.js
  cli/src/commands/v2-migrations/20190509000000_migrate_null_resetTokens.js
  cli/src/commands/v2-migrations/index.js
  lib/models/user.js
  lib/templates/emails/newUserReset.html
Labels: QA PASSED, Type: Fix

#1376 fix(Statement count): Await save
  cli/src/commands/updateStatementCount.js
Labels: Type: Fix

#1352 Add color picker
  lib/constants/visualise.js
  lib/models/organisation.js
  ui/src/components/ColorPicker/CustomColorPicker.js
  ui/src/components/ColorPicker/index.js
  ui/src/components/TabbedQueriesBuilder/index.js
  ui/src/redux/modules/queryBuilder.js
Labels: QA PASSED, Type: Feature

#1382 fix(SideNav) push down help centre
  ui/src/components/SideNavFooter/index.js
  ui/src/components/SideNavFooter/sidenavfooter.css
  ui/src/containers/SideNav/index.js
  ui/src/containers/SideNav/sidenav.css
Labels: Type: Fix

#1378 fix(Widget): no type visualisation in Widget
  ui/src/containers/Widget/index.js
  ui/src/redux/modules/visualise.js
Labels: Type: Fix

#1381 feat(Dashboard) add templates
  lib/routes/index.js
  ui/src/containers/Dashboard/index.js
  ui/src/containers/DashboardGrid/index.js
  ui/src/containers/DashboardTemplates/BlankDashboard.js
  ui/src/containers/DashboardTemplates/GettingStarted.js
  ui/src/containers/DashboardTemplates/TemplateCard.js
  ui/src/containers/DashboardTemplates/index.js
  ui/src/containers/DashboardTemplates/styles.css
  ui/src/containers/Dashboards/index.js
  ui/src/containers/VisualiseForm/StatementsForm/NewVisualisation/TemplateCard.js
  ui/src/redux/modules/dashboard/blankDashboard.js
  ui/src/redux/modules/dashboard/gettingStarted.js
  ui/src/redux/modules/dashboard/index.js
  ui/src/redux/modules/sagas.js
Labels: Type: Feature
